In [1]:
import numpy as np

In [ ]:
# Python list - musíš projít každý prvek
result = [x * 2 for x in my_list]

#NumPy - Přímá matematická operace na celém poli
result = my_array *2

In [3]:
import numpy as np
import time

n = 10_000_000
py_list = list(range(n))
np_array = np.arange(n)

#Varianta 1 - klasická smyčka
result_loop = [0] * n
start = time.time()
for i in range(n):
    result_loop[i] = py_list[i] * 2
t_loop = time.time() - start

#Varianta 2 - list comprehension
start = time.time()
result_lc = [x * 2 for x in py_list]
t_lc = time.time() - start

#Varianta 3 - NumPy vektorizace
start = time.time()
result_np = np_array * 2
t_np = time.time() - start

print(f"For smyčka: {t_loop:.3f} s")
print(f"List comprehension: {t_lc:.3f} s")
print(f"NumPy: {t_np:.3f} s")
print(f"\nNumPy vs For smyčka: {t_loop / t_np:.0f}x")
print(f"Numpy vs List comprehension: {t_lc / t_np:.0f}x")

For smyčka: 1.572 s
List comprehension: 3.656 s
NumPy: 0.564 s

NumPy vs For smyčka: 3x
Numpy vs List comprehension: 6x


In [6]:
import numpy as np
# ze seznamu
a = np.array([1, 2, 3, 4, 5])
a

array([-0.09 ,  0.011,  0.148,  0.036,  0.255, -0.127,  0.027,  0.016])

In [11]:
# Číslená řada - arange(start, stop, krok)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
#Rovnoměrně rozložené hodnoty - ideální pro časové osy
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#Gaussův šum - realistické biomedicínské hodnoty
noise = np.random.normal(loc=0, scale =0.1, size=8)
np.round(noise, 3)

array([ 0.082, -0.147,  0.003, -0.248, -0.086, -0.263,  0.047, -0.033])

In [10]:
signal = np.array([0.5, 1.2, 1.8, 0.9, 2.1, 1.5, 0.7, 1.1])
signal.shape, signal.ndim, len(signal)
signal[0], signal[-1]
signal[2:5]
signal[::2]

array([0.5, 1.8, 2.1, 0.7])

In [16]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
matrix.shape

(3, 3)

In [18]:
matrix[1, 2]

np.int64(6)

In [19]:
matrix[0, :]

array([1, 2, 3])

In [20]:
matrix[:, 1]

array([2, 5, 8])

In [22]:
a_int = np.array([1, 2, 3])
a_int.dtype

dtype('int64')

In [24]:
a_float = np.array([1.0, 2.0, 3.0])
a_float.dtype

dtype('float64')

In [26]:
a32 = np.zeros(4, dtype=np.float32)
print(f"dtype: {a32.dtype} paměť na prvek: {a32.itemsize} B")

dtype: float32 paměť na prvek: 4 B


In [27]:
a_int.astype(float)

array([1., 2., 3.])

In [28]:
flat = np.arange(12)
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
flat.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
flat.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [31]:
flat.reshape(1, -1).shape, flat.reshape(-1, 1).shape

((1, 12), (12, 1))

In [33]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80])
data[[0, 2, 5]]

array([10, 30, 60])

In [34]:
data[[5, 0, 5, 2]]

array([60, 10, 60, 30])

In [35]:
mereni = np.array([[120, 80, 72],
                   [135, 88, 90],
                   [118, 76, 65],
                   [145, 95, 88]])

mereni[[0, 2]]

array([[120,  80,  72],
       [118,  76,  65]])

In [36]:
mask = np.array([True, False, True, False, True, False, True, False])
data[mask]

array([10, 30, 50, 70])

In [37]:
data > 40

array([False, False, False, False,  True,  True,  True,  True])

In [38]:
data[data > 40]

array([50, 60, 70, 80])

In [39]:
data[(data > 20) & (data < 70)]

array([30, 40, 50, 60])

In [40]:
a = np.array([1.0, 2.0, 3.0, 4.0])
b = np.array([0.5, 0.5, 0.5, 0.5])
a + b

array([1.5, 2.5, 3.5, 4.5])

In [41]:
a ** 2

array([ 1.,  4.,  9., 16.])

In [42]:
np.round(np.sqrt(a), 3)

array([1.   , 1.414, 1.732, 2.   ])

In [43]:
print(f"sum: {a.sum()} mean: {a.mean()} std: {a.std():.3f}")
print(f"min: {a.min()} max: {a.max()}")

sum: 10.0 mean: 2.5 std: 1.118
min: 1.0 max: 4.0


In [44]:
a[a > 2].mean()

np.float64(3.5)

In [46]:
mereni = np.array([[120, 80, 72],
                   [135, 88, 90],
                   [118, 76, 65],
                   [145, 95, 88]])
print("Průměr přes všechna data:", mereni.mean())
print("Průměr po sloupcích (axis=0:", mereni.mean(axis=0))
print("Průměr po řádcích (axis=1):", mereni.mean(axis=1))

Průměr přes všechna data: 97.66666666666667
Průměr po sloupcích (axis=0: [129.5   84.75  78.75]
Průměr po řádcích (axis=1): [ 90.66666667 104.33333333  86.33333333 109.33333333]


In [47]:
tf = np.array([72, 90, 65, 88])

idx_max = tf.argmax()
idx_min = tf.argmin()

print(f"Nejvyšší TF má pacient {idx_max} (hodnota {tf[idx_max]})")
print(f"Nejnižší TF má pacient {idx_min} (hodnota {tf[idx_min]})")

Nejvyšší TF má pacient 1 (hodnota 90)
Nejnižší TF má pacient 2 (hodnota 65)


In [48]:
# argmax/argmin lze použít i s axis – index extrému v každém řádku/sloupci matice
print("Index maxima v každém sloupci:", mereni.argmax(axis=0))
print("Index maxima v každém řádku: ", mereni.argmax(axis=1))

Index maxima v každém sloupci: [3 3 1]
Index maxima v každém řádku:  [0 0 0 0]


In [60]:
import numpy as np
#1. Načtení dat
data = np.load("pacienti.npy")
print(data.shape)
print(data[:5, :])
#2. Průměr a std každého ukazatele
print(data.mean(axis=0))
print(data.std(axis=0))
#3. Pacienti s hypertenzí (sys >= 140)
mask = data[:, 0] >= 140
print(data[mask])
print(data[mask].shape[0])
#4. Pulzní tlak jako nový sloupec
pulsepress = data[:, 0] - data[:, 1]
data = np.column_stack((data, pulsepress))
#5. Pacient s nejvyšší tepovou frekvencí
idx = data[:, 2].argmax()
print(idx)
print(data[idx, :])

(20, 3)
[[129.6  78.2  93. ]
 [109.4  73.2  72. ]
 [136.3  92.2  61. ]
 [139.1  78.5  89. ]
 [ 95.7  75.7  80. ]]
[124.51   81.105  77.   ]
[12.72807527  7.73869983 11.28273017]
[[141.9  71.9  70. ]]
1
0
[129.6  78.2  93.   51.4]
